#ifndef __REVISION_SQL_H__
#define __REVISION_SQL_H__
 #define REVISION_DB_REALMD "required_14028_01_realmd_account_locale_agnostic"
 #define REVISION_DB_CHARACTERS "required_14025_00_characters_item_instance_data_drop"
 #define REVISION_DB_MANGOS "required_14029_01_mangos_creature_template_spells_extension"
#endif // __REVISION_SQL_H__
