ALTER TABLE db_version CHANGE COLUMN required_12269_03_mangos_fishing_loot_template required_12269_04_mangos_reference_loot_template bit;

ALTER TABLE reference_loot_template DROP COLUMN lootcondition, DROP COLUMN condition_value1, DROP COLUMN condition_value2;
